### ISSUE TITLE
Can't create archive. 

### ISSUE THREAD

**Issue by lebacql** [helios-ag/FMElfinderBundle#220]
Hello I'm using symfony 2.8 on a Debian 8 OS. When I try to archive document a pop-up Windows Error appear with this message : Unable to connect to backend.

**Comment by helios-ag** [comment]
Hi @lebacql 
Issue confirmed, working on it

**Comment by helios-ag** [comment]
Fixed in https://github.com/helios-ag/ElFinderPHP/commit/1117919c0f2bc6958ee8d77af365c25e0d17ecd7

**Comment by lebacql** [comment]
Thanks for your patch. But the problem persists. My version on the server of PHP is 5.6, should I downgrade it ?

**Comment by helios-ag** [comment]
I answered in #225 , probably almost same issue with config/platform node in composer.json that doesn't allow to fetch latest elfinder-php library
